### ISSUE TITLE
Add design to 24hr stats

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/dex-explorer#107]
<img width="375" alt="Screenshot 2024-10-24 at 4 34 59 PM" src="https://github.com/user-attachments/assets/0b3b852b-852d-4d14-894c-61b9e3119345">

Reference: https://www.figma.com/design/xWsVprkEgEihweVN9isrGQ/DEX-(Incl.-UI-Lib)?node-id=3658-145100&node-type=canvas&t=NYogohDveZXB9V4J-0

**Comment by cronokirby** [comment]
https://github.com/penumbra-zone/penumbra/blob/main/crates/bin/pindexer/src/dex_ex/schema.sql#L50

I think the dex explorer schema in pindexer should already be able to provide what's needed here.
