### ISSUE TITLE
Explore page header

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/dex-explorer#110]
Desktop Skeleton:

<img width="760" alt="Screenshot 2024-10-24 at 4 55 30 PM" src="https://github.com/user-attachments/assets/daa8c52f-edde-4ac9-a0e6-9f99bad064b9">

Desktop Loaded state:
<img width="754" alt="Screenshot 2024-10-24 at 4 55 50 PM" src="https://github.com/user-attachments/assets/54f657cc-c36f-473e-a9d2-4d17c1b89a11">

Mobile skeleton:

<img width="237" alt="Screenshot 2024-10-24 at 4 56 29 PM" src="https://github.com/user-attachments/assets/fa75e5d9-a759-4c22-b365-dee7c300758b">

Mobile Loaded state:

<img width="248" alt="Screenshot 2024-10-24 at 4 56 45 PM" src="https://github.com/user-attachments/assets/e785936c-a043-493b-b640-d439f206ce61">

Add penumbra background image as well 🌔 

Reference: https://www.figma.com/design/xWsVprkEgEihweVN9isrGQ/DEX-(Incl.-UI-Lib)?node-id=3658-145100&node-type=canvas&t=NYogohDveZXB9V4J-0

**Comment by cronokirby** [comment]
at a first glance we can calculate these with simple queries of the pindexer summary table (take the max over all pairs, sum over all pairs, etc.), except for the number of trades, that's missing (can be added).

However, there's a genuine bit of exploration / thinking about how exactly we put things into a common numeraire (in this mockup, dollars). e.g. for the UM / OSMO pair, there's a volume in terms of UM or in terms of OSMO (the volume measures how much is trading in one direction or the other, so not just symmetrized over the price). In general, a pair might exist without there being a known price in terms of USDC; we could ignore these for the summary, but we should be cognizant that we're doing so.
