### ISSUE TITLE
Explore page: trading pairs

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/dex-explorer#111]
Desktop loading skeleton:

<img width="899" alt="Screenshot 2024-10-24 at 4 59 40 PM" src="https://github.com/user-attachments/assets/db624274-0de3-40a6-bef3-7b0e0d1f14f6">

Desktop loaded state:
<img width="908" alt="Screenshot 2024-10-24 at 5 00 12 PM" src="https://github.com/user-attachments/assets/a4284f06-92f4-48d8-a3ca-4fcf139d548e">

Mobile loading skeleton:
<img width="305" alt="Screenshot 2024-10-24 at 5 00 37 PM" src="https://github.com/user-attachments/assets/613527c5-225b-4c88-b3f7-af2337142bd3">

Mobile loaded state:
<img width="376" alt="Screenshot 2024-10-24 at 5 01 25 PM" src="https://github.com/user-attachments/assets/89de8d4b-93cb-44b9-be17-38b5edd8ec73">

Reference: https://www.figma.com/design/xWsVprkEgEihweVN9isrGQ/DEX-(Incl.-UI-Lib)?node-id=3658-145100&node-type=canvas&t=NYogohDveZXB9V4J-0

**Comment by cronokirby** [comment]
Like with #107, I think the table in pindexer's dex explorer schema has all the info we need already? https://github.com/penumbra-zone/penumbra/blob/main/crates/bin/pindexer/src/dex_ex/schema.sql#L50
