### ISSUE TITLE
db: new schema for dex events, `dex_ex_candlesticks` no longer exists

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/dex-explorer#132]
The `pindexer` database schema no longer includes a `dex_ex_candlesticks` table, as of merge of https://github.com/penumbra-zone/penumbra/pull/4917. The dex-explorer database interface should be updated to match the latest schema. 

Also affected are queries against the `dex_ex_summary` table, which was also removed (#126).

See related discussion for motivation in https://github.com/penumbra-zone/penumbra/issues/4914

**Comment by VanishMax** [comment]
@conorsch when will the new tables be applied to pindexer? For now `dex_ex_summary` still seems to exist
