### ISSUE TITLE
Merge candle logic update

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/dex-explorer#151]
@cronokirby to update pindexer to handle candlestick merging. The API route can remove all merge logic and rely on the single-direction query from the database.

Secondly, the backend should pass base-denominated values back to the frontend who is responsible for doing the base->display conversions.

**Comment by cronokirby** [comment]
I think on the dex explorer side the change should just be to only make one database query, and pindexer itself should worry about making the chart have both pieces of information. On the dex ex side we should just need the frontend to fill in empty candles (on the frontend, to not transfer that data)

**Comment by grod220** [comment]
Ah, in that case, will revise the description and please ping this issue when the merging can be removed from the API please 🙏
