### ISSUE TITLE
Post-disconnect asset list persisting

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/dex-explorer#157]
Steps to reproduce:
1. Connect wallet that has a balance
2. Click asset selector and note token balances
3. Disconnect wallet
4. Click asset selector tab and the previous connected wallet's balances persist (refreshing fixes it)

Very likely a mobx store not re-rendering after the connection state changes

Example after disconnecting:
<img width="625" alt="Screenshot 2024-11-22 at 4 42 57 PM" src="https://github.com/user-attachments/assets/87208d08-b376-4189-ac69-0263a3d212d1">

**Comment by hdevalence** [comment]
Rather than doing a specific fix I think it would be fine to just reload the page on disconnect. Guaranteed way to wipe state
