### ISSUE TITLE
Chart persists prices after updates

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/dex-explorer#174]
<img width="941" alt="Screenshot 2024-12-03 at 11 55 09 PM" src="https://github.com/user-attachments/assets/537293d4-513e-4a1c-9b9d-3df33648ca90">

After leaving the browser tab open for a while, the chart accumulates price info. Looks like the old price indicator line isn't getting cleared.

**Comment by grod220** [comment]
Related to https://github.com/penumbra-zone/dex-explorer/issues/150. When react re-renders the component, the right-hand price indicator isn't being cleared.
