### ISSUE TITLE
chain id env var not being read correctly

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/dex-explorer#182]
Right now if I navigate to https://dex-explorer.mainnet.plinfra.net/explore I'm met with an error message about the env var `PENUMBRA_CHAIN_ID` not being set:

![dex-chain-id-not-found](https://github.com/user-attachments/assets/95e12220-fc44-4540-82b7-1b9bbf2e091c)

When I check on the deployed instance, that env var is in fact set correctly:

```
<<K9s-Shell>> Pod: mainnet/dex-explorer-74d97bf468-lhr49 | Container: plapp
/app $ echo $PENUMBRA_CHAIN_ID
penumbra-1
/app $
```

If I run the dev env locally on my machine, hooked up to mainnet indexing db, then I see a different error message:

> The number 196317320277.29083 cannot be converted to a BigInt because it is not an integer

![dex-bigint](https://github.com/user-attachments/assets/966fe120-a847-4fce-98ab-e4cf6b0254d3)

I'm not sure why the behavior is different between the built site vs the dev env, but we've seen instances in the past where env vars are handled differently between those environments, e.g. https://github.com/penumbra-zone/dex-explorer/issues/121.

**Comment by grod220** [comment]
@VanishMax think you fixed this right?

**Comment by VanishMax** [comment]
@grod220 yes, we can close it now
