### ISSUE TITLE
market buy and sell UI bugs

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/dex-explorer#196]
- misaligned cursor within input field,
- displays ghost prices,
- misplaced elements leading to inconsistent visual alignment

---------------------------

<img width="281" alt="Screenshot 2024-12-10 at 1 42 40 AM" src="https://github.com/user-attachments/assets/658b8dcf-98d9-4777-8edf-7077e9acb6ae">

---------------------------

<img width="290" alt="Screenshot 2024-12-10 at 1 42 54 AM" src="https://github.com/user-attachments/assets/8f2cdffc-a9b3-44e2-9d1a-5b096b756d62">

---------------------------

<img width="290" alt="Screenshot 2024-12-10 at 1 43 19 AM" src="https://github.com/user-attachments/assets/1ce7bd8a-8606-4e37-a653-62e5b581ee40">

---------------------------

<img width="291" alt="Screenshot 2024-12-10 at 1 46 16 AM" src="https://github.com/user-attachments/assets/22bd715d-bdf3-4504-88b8-00ecacbf0275">

**Comment by cronokirby** [comment]
For the ghost prices issue https://github.com/penumbra-zone/dex-explorer/pull/181/commits/05b8d164cd1f4cc7da34a2dc88a4d3d9763f2d4c it was just a matter of using the wrong name for the tailwind class
