### ISSUE TITLE
offline network errors 

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/dex-explorer#219]
intentionally disconnected wifi to see more error states. We should implement some kind of graceful fallback UI that hides or disables features that rely on network connectivity, or maybe display an offline modal, or backfilling these components with [loading skeletons](https://github.com/penumbra-zone/dex-explorer/issues/106) instead of displaying loading errors?

<img width="1728" alt="Screenshot 2024-12-13 at 4 54 48 PM" src="https://github.com/user-attachments/assets/24a83b6c-69a0-432c-bc18-c95b4479ee97" />

**Comment by grod220** [comment]
Don't think we need a non-wifi-connected UI state for our components and we can just do https://github.com/penumbra-zone/dex-explorer/issues/211 to match what the error states should be rendered like.

**Comment by TalDerei** [comment]
missed that error states issue, that's more in the spirit of a resolution I had in mind.
