### ISSUE TITLE
Remove dependency on raw events database

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/dex-explorer#49]
We want to remove the dependency of this code on the raw events database, instead using a derived database created with `pindexer`.

**Comment by aubrika** [comment]
Currently blocked by some uncertainty around needs: Is the code currently relying on the raw events intended to persist? There isn't an existing Figma / design plan for an LP update page for V2, so we aren't quite sure what the requirements are - to what extent will the indexer be required in the V2 design?

This may be best determined in a synchronous meeting, happy to DM about it.
