### ISSUE TITLE
Implement Market Buy

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/dex-explorer#86]
Requirements:
- Navigation for Market & Limit
- Initiates with zero buy/pay with input
- Buy is an estimate that pulls from a grpc request to node SimulateTradeRequest (alt: from route-book)
- Pay with is the input
- Displays fees
  - Free Trading Fees (info about how LPs set price)
  - Gas fees
- Slider that who's setting reacts to input and also impacts it on change
- Display balance in wallet (pulls from global account # in mobx store)
- Issues Toasts for states:
  - Build
  - Awaiting on chain
  - Success + tx details page link (TBD)

![Image](https://github.com/user-attachments/assets/09256dd8-5b6f-437a-bca3-d94dfa338911)

**Comment by TalDerei** [comment]
opened https://github.com/penumbra-zone/dex-explorer/issues/140 to track relevant follow-up work
